name: publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1
      - uses: actions/setup-go@v2.1.5
      - run: go version
      - name: Set up Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: 1.16

      - name: Vet
        working-directory: claat
        run: go vet ./...

      - name: Build
        working-directory: claat
        run: go build -v ./...
      - run: |
          claat/claat version
          mkdir codelabs
          for f in `ls markdowns/*/*.md`; do 
          claat/claat export -prefix https://matthiasdruwe.github.io/codelabs/elements -o codelabs/ $f;
          done
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          cd site
          npm install
          npm run dist
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          BRANCH: gh-pages
          FOLDER: site/dist
          CLEAN: true
